name: Kenwood Chef API
version: 0.1.0
slug: kenwood-chef-api
description: API Replacement for the Kenwood chef
url: https://github.com/simmsb/kenwood-chef-api
startup: services
init: false
arch:
- aarch64
- amd64
hassio_api: true
map:
  - config:rw
options:
  env_vars: []
  PGID: 0
  PUID: 0
image: ghcr.io/simmsb/kenwood-api/{arch}
environment:
  DATABASE_URL: /config/db.sqlite?mode=rwc
ports:
  443/tcp: 443
  8080/tcp: 8080
ports_description:
  443/tcp: Device API
  8080/tcp: Recipe editor
schema:
  env_vars:
    - name: match(^[A-Za-z0-9_]+$)
      value: str?
  PGID: int
  PUID: int
