[package]
name = "types"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.42", features = ["serde"] }
jiff = { version = "0.2.16", default-features = false, features = ["serde", "std"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
