[package]
name = "ui"
version = "0.1.0"
authors = ["Ben Simms <ben@bensimms.moe>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
types = { path = "../types" }
db = { path = "../db", optional = true }
dioxus = { version = "0.7.2", features = ["router", "fullstack"] }
dioxus-query = "0.9.0"
dioxus-primitives = { git = "https://github.com/DioxusLabs/components", version = "0.0.1", default-features = false, features = ["router"] }
sea-orm = { version = "^2.0.0-rc", features = ["sqlx-sqlite", "macros", "runtime-tokio-rustls", "with-json"], optional = true }
tokio = { version = "1.48.0", features = ["full"], optional = true }
tracing = { version = "0.1.43", features = ["async-await"] }
jiff = { version = "0.2.16", default-features = false, features = ["serde", "std"] }

[features]
default = ["server", "web"]
web = ["dioxus/web", "dioxus-primitives/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
server = ["dioxus/server", "dep:db", "dep:sea-orm", "dep:tokio"]
